# Generated by Django 2.2.1 on 2019-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190620_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(blank=True, default=5.5, null=True),
        ),
    ]
