# Generated by Django 2.2.1 on 2019-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
