# Generated by Django 2.2.1 on 2019-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
