# Generated by Django 2.2.1 on 2019-07-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_post_read_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_count',
        ),
    ]
